Repository VariantEffect/mavedb-ui, pull requests merged in 2024-09, with the labels that each got.

#264 Remove duplicate function.
  src/components/screens/ScoreSetCreator.vue
Labels: type: maintenance

#270 Vrs map integration
  src/components/screens/ScoreSetView.vue
Labels: type: feature

#269 Add create score set in experiment view page
  src/components/screens/ExperimentView.vue
  src/components/screens/ScoreSetCreator.vue
  src/router/index.js
Labels: type: bug
