Repository VariantEffect/mavedb-ui, pull requests merged in 2024-10, with the labels that each got.

#263 Wizardification of creating experiment workflow
  src/components/screens/ExperimentCreator.vue
  src/components/screens/ExperimentEditor.vue
  src/router/index.js
Labels: type: enhancement, app: frontend

#247 Wizardify Target Gene Creation
  src/components/screens/ScoreSetCreator.vue
Labels: type: enhancement, app: frontend

#276 Score Range UI
  src/components/screens/ScoreSetCreator.vue
  src/components/screens/ScoreSetEditor.vue
  src/components/screens/ScoreSetView.vue
Labels: type: feature, workstream: pillar, app: frontend

#278 Heatmap Color Bar
  package-lock.json
  package.json
  src/components/ScoreSetHeatmap.vue
  src/lib/heatmap.ts
Labels: type: bug, type: enhancement

#279 Refresh Dependencies for High Severity Dependabot Alerts
  package-lock.json
  requirements.txt
Labels: type: maintenance, app: frontend

#291 Solve any users can click edit or add button in experiment, score set and experiment set pages.
  src/components/screens/ExperimentSetView.vue
  src/components/screens/ExperimentView.vue
  src/components/screens/ScoreSetView.vue
Labels: type: enhancement, app: frontend
