Repository VariantEffect/mavedb-ui, pull requests merged in 2025-08, with the labels that each got.

#429 'Report an Issue With This DataSet' (Site Footer)
  src/assets/layout.css
  src/assets/logo-mavedb-transparent.png
  src/components/layout/DefaultLayout.vue
  src/components/layout/Footer.vue
  src/components/screens/ScoreSetView.vue
Labels: type: enhancement, app: frontend

#417 Davereinhart/protein visualization
  package-lock.json
  package.json
  src/components/ProteinStructureView.vue
  src/components/ScoreSetHeatmap.vue
  src/components/ScoreSetVisualizer.vue
  src/components/screens/ScoreSetView.vue
  src/lib/chart-export.ts
  src/lib/heatmap.ts
Labels: type: feature, app: frontend

#433 Score Range Boundary Handling
  package-lock.json
  package.json
  src/components/RangeTable.vue
  src/components/VariantMeasurementView.vue
  src/components/screens/ScoreSetCreator.vue
  src/components/screens/ScoreSetEditor.vue
  src/lib/ranges.ts
  src/main.js
Labels: type: enhancement, workstream: clinical, app: frontend

#436 Release 2025.3.0
  package-lock.json
  package.json
  src/assets/layout.css
  src/assets/logo-mavedb-transparent.png
  src/components/CalibrationTable.vue
  src/components/OddsPathTable.vue
  src/components/ProteinStructureView.vue
  src/components/RangeTable.vue
  src/components/ScoreSetHeatmap.vue
  src/components/ScoreSetHistogram.vue
  src/components/ScoreSetVisualizer.vue
  src/components/VariantMeasurementView.vue
  src/components/layout/DefaultLayout.vue
  src/components/layout/Footer.vue
  src/components/screens/ScoreSetCreator.vue
  src/components/screens/ScoreSetEditor.vue
  src/components/screens/ScoreSetView.vue
  src/components/screens/SearchVariantsScreen.vue
  src/components/screens/VariantScreen.vue
  src/components/screens/WizardCompletionView.vue
  src/lib/calibrations.ts
  src/lib/chart-export.ts
  src/lib/heatmap.ts
  src/lib/ranges.ts
  src/main.js
  src/router/index.js
Labels: core: release
